formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
linters:
  default: standard
  enable:
    - exhaustive
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - nonamedreturns
    # - paralleltest
    - predeclared
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    forbidigo:
      forbid:
        - msg: use colerr instead of fmt.Errorf
          pattern: ^fmt\.Errorf$
    paralleltest:
      ignore-missing-subtests: true
version: '2'
