formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
linters:
  default: standard
  enable:
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - nonamedreturns
    # - paralleltest
    - predeclared
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    exhaustive:
      # Program elements to check for exhaustiveness.
      check:
        - switch
        - map
      # Presence of "default" case in switch statements satisfies exhaustiveness,
      # even if all enum members are not listed.
      default-signifies-exhaustive: true
    paralleltest:
      ignore-missing-subtests: true
version: '2'
